version: '3'

services:
  balance-manager:
    image: registry.cn-hangzhou.aliyuncs.com/iuin/balance-manager:latest
    container_name: balance-manager
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    networks:
      - balance-network
    restart: always

networks:
  balance-network:
    driver: bridge 