version: '3'

services:
  balance-manager:
    image: ${DOCKER_IMAGE:-balance-manager:local}
    container_name: ${CONTAINER_NAME:-balance-manager}
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    volumes:
      - ..:/app
    networks:
      - balance-network
    restart: always

networks:
  balance-network:
    driver: bridge 